### PR TITLE
Add support for random secret generation

### PR DESCRIPTION
**Pull request by rubendg**
Adds support for random secret generation. The use case for this is e.g. generating the input key for a symmetric encryption cipher like AES.

### CODE REVIEW

**Comment by mvanholsteijn** [comment]
Hi Ruben, it feels a bit like Random should be its own custom resource type, like RSAKey etc.

**Comment by rubendg** [comment]
I'll rework it to a distinct resource type 👍

**Comment by mvanholsteijn** [comment]
Great! May I recommend to look at the RSAkey provider for inspiration.

**Comment by rubendg** [comment]
@mvanholsteijn I've reworked it a bit, can you have another look?

**Comment by mvanholsteijn** [comment]
@rubendg thank you for your contribution! Released as version 1.4.4.

**Pull request merged**
